EXPORT_TABLE_SCHEMAS = [
    'DASHBOARD_DATABASE.CLIENT_DATA',
    'MOROCH_DASHBOARDS_DATABASE.ADWORDS',
    'MOROCH_DASHBOARDS_DATABASE.DFA_CAMPAIGN_MANAGER',
    'MOROCH_DASHBOARDS_DATABASE.FACEBOOK',
    'MOROCH_DASHBOARDS_DATABASE.FTP',
    'MOROCH_DASHBOARDS_DATABASE.GA',
    'MOROCH_DASHBOARDS_DATABASE.MOROCH_FACEBOOK_AD_ACCOUNT',
    'MOROCH_DASHBOARDS_DATABASE.MOROCH_GOOGLE_SEARCH_CONSOLE',
    'MOROCH_DASHBOARDS_DATABASE.SHEN_GOOGLE_SEARCH_CONSOLE',
    'MOROCH_DASHBOARDS_DATABASE.SNAPCHAT_ADS',
    'PLANET_FITNESS.CLIENT_DATA',
    'PLANET_FITNESS.CLIENT_KEYS',
    'PLANET_FITNESS.DCM',
    'PLANET_FITNESS.GA',
    'PLANET_FITNESS.PAID_SOCIAL',
    'PLANET_FITNESS.SEM',
    'PLANET_FITNESS.POLYGRAPHMOROCHDATA',
    'PLANET_FITNESS.POLYGRAPHMOROCHDATASTATS',
]


LIST_TABLES_SQL = """
SELECT DISTINCT
TABLE_NAME
FROM {database}.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA ilike '{schema}'
"""