from os import environ

SNOWFLAKE_DATABASE = environ["SNOWFLAKE_DATABASE"]
SNOWFLAKE_USER = environ["SNOWFLAKE_USER"]
SNOWFLAKE_PW = environ['SNOWFLAKE_PW']
SNOWFLAKE_ACCOUNT = environ['SNOWFLAKE_ACCOUNT']